# This file is part of a Spipu Bundle
#
# (c) Laurent Minguet
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
parameters:
    spipu.core.encryptor.key_pair: "please generate a new key pair with spipu:encryptor:generate-key-pair"

services:
    Spipu\CoreBundle\Service\AsynchronousCommand:
        arguments:
            - '@Spipu\CoreBundle\Service\ProcessFactory'
            - '@filesystem'
            - '%kernel.project_dir%'
            - '%kernel.logs_dir%'

    # Role Definition
    Spipu\CoreBundle\Service\RoleDefinition:
        tags: ['spipu.user.role']

    # External Services
    Spipu\CoreBundle\Service\MailManager:
        arguments:
            - '@mailer.mailer'
            - '@twig'

    Spipu\CoreBundle\Service\HasherFactory:
        arguments: []

    Spipu\CoreBundle\Service\EncryptorInterface:
        class: Spipu\CoreBundle\Service\Encryptor
        arguments:
            - '%spipu.core.encryptor.key_pair%'

    Spipu\CoreBundle\Service\SluggerInterface:
        class: Spipu\CoreBundle\Service\Slugger

    Spipu\CoreBundle\Service\Filesystem:
        arguments: []

    Spipu\CoreBundle\Service\FinderFactory:
        arguments: []

    Spipu\CoreBundle\Service\ProcessFactory:
        arguments: []

    Spipu\CoreBundle\Service\RoleDefinitionList:
        arguments:
            - !tagged 'spipu.user.role'

    # Internal Services
    Spipu\CoreBundle\Fixture\ListFixture:
        arguments:
            - !tagged 'spipu.fixture'

    Spipu\CoreBundle\Assets\ListAsset:
        arguments:
            - !tagged 'spipu.asset'

    Spipu\CoreBundle\Service\Assets:
        arguments:
            - '@Spipu\CoreBundle\Service\Filesystem'
            - '@Spipu\CoreBundle\Service\FinderFactory'
            - '@Spipu\CoreBundle\Assets\ListAsset'
            - '%kernel.project_dir%'

    Spipu\CoreBundle\Command\FixturesLoadCommand:
        arguments:
            - '@Spipu\CoreBundle\Fixture\ListFixture'
        tags: ['console.command']

    Spipu\CoreBundle\Command\FixturesRemoveCommand:
        arguments:
            - '@Spipu\CoreBundle\Fixture\ListFixture'
        tags: ['console.command']

    Spipu\CoreBundle\Command\AssetsInstallCommand:
        arguments:
            - '@Spipu\CoreBundle\Service\Assets'
        tags: ['console.command']

    Spipu\CoreBundle\Command\EncryptorKeyPairCommand:
        tags: ['console.command']
